# docker compose example
# exposes restful_relay service on port 8083
# example command:  docker-compose -f docker-compose.yml up
---
version: '3'
services:
  dadjokes:
    image: docker.io/yesinteractive/restfulrelay
    container_name: restful_relay
    restart: always
    ports:
      - "8083:443"
